SUPER_CONFIG_PATH: ./configs/IOMOT_dancetrack.yaml

DATASETS: [MOT17, CrowdHuman, CrowdHuman]
DATASET_SPLITS: [train,train,val]
DATASET_WEIGHTS: [2,1,1]

SAMPLE_LENGTHS: [20]
SAMPLE_INTERVALS: [2]
MAX_TEMPORAL_LENGTH: 20
NUM_WORKERS: 4

AVAILABLE_GPUS: 0,
USE_DISTRIBUTED:  True

PERTRAIN: True
PERTRAIN_PATH:   /home1/lcy/FIP-v3/outputs/MOT17withCH/checkpoint_37.pth


OUTPUTS_DIR: ./outputs/MOT17withCH_test

AUG_MAX_SIZE: 1536
AUG_RESIZE_SCALES: [608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]

INFERENCE_MODEL: /home1/lcy/FIP-v3/outputs/MOT17withCH/checkpoint_50.pth
INFERENCE_DATASET: MOT17
INFERENCE_SPLIT: test
INFERENCE_MAX_SIZE: 1536


DET_THRESH: 0.5
NEWBORN_THRESH: 0.5
ID_THRESH: 0.02
ACCUMULATE_STEPS: 8

EPOCHS: 60 #100
SCHEDULER_MILESTONES: [30, 40, 50] #[60, 80, ]
LR_WARMUP_EPOCHS: 2

NUM_ID_VOCABULARY: 200
TRAINING_NUM_ID: 80
